silent-mobs:
  enabled: true
  name: "silence"

anti-enderman-grief:
  enabled: true

commands:
  titancraftqol:
    description: Reloads TitanCraftQOL config
    usage: /titancraftqol reload
    permission: titancraftqol.admin
