silent-mobs:
  enabled: false
  name: "silence"

anti-enderman-grief:
  enabled: false

no-anvil-limit:
  enabled: false

cauldron-concrete-conversion:
  enabled: false

silk-touch:
  budding-amethyst: false
  reinforced-deepslate: false

baby-mobs:
  enabled: false
  name: "baby"